name: Pipeline App Service and Docker

on:
  push:
    branches:
      - "**"
  pull_request:
    branches: ["master", "development"]
  create:

env:
  IMAGE_NAME: druida-githubactions-angular
  IMAGE_VERSION: 1.0.1

jobs:
  DeployDev:
    name: Deploy to development
    environment: Dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Az CLI login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: ACR authentication
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
      - name: Docker Build & Push to ACR
        run: |
          docker build . -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} -t ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }} --env apiUrl=${{ secrets.API_URL }}
      - name: "Deploy to Azure Web App for Container"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ap-demo-gha-docker-dev-001
          images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}
